version: '3'

services:
  postgres_slh_lab2:
    container_name: postgres_slh_lab2
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASS
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432
